@startuml
'https://plantuml.com/class-diagram

abstract class Interface
abstract Game
interface Objet
interface Item
interface personnage

Interface <|-- Game
Game <|-- Objet
Objet <|-- Item
Objet <|-- personnage

class Interface {
Object[] elementData
size()
}

enum Timer {
DAYS
HOURS
MINUTES
SECONDS
}

@enduml